apps/sales/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('get_order/', login_required(get_order), name='get_order'),
    path('sales/', login_required(SalesList.as_view()), name='sales'),
    path('sales_save/', login_required(sales_save), name='sales_create'),

    path('purchase_save/', login_required(purchase_save), name='purchase_save'),
    path('purchase/', login_required(PurchaseList.as_view()), name='purchase'),

    path('pawns/', login_required(PawnsList.as_view()), name='pawns'),
    path('modal_pawns/', login_required(modal_pawns), name='modal_pawns'),
    path('pawns_save/', login_required(pawns_save), name='pawns_save'),

    path('returns/', login_required(ReturnList.as_view()), name='returns'),
    path('get_pawns_by_provider/', login_required(get_pawns_by_provider), name='get_pawns_by_provider'),
    path('modal_return_pawns/', login_required(modal_return_pawns), name='modal_return_pawns'),
    path('return_save/', login_required(return_save), name='return_save'),

    path('delete_order_detail/', login_required(delete_order_detail), name='delete_order_detail'),
    path('get_sales_month/', login_required(get_sales_month), name='get_sales_month'),
    path('get_sales_week/', login_required(get_sales_week), name='get_sales_week'),
    path('report/', login_required(ReportList.as_view()), name='report'),
    path('get_orders/', login_required(get_orders), name='get_orders')
]

ivanet/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include

from apps.users.views import Home, logout_user, Login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_required(Home.as_view()), name='home'),
    path('accounts/login/', Login.as_view(), name='login'),
    path('logout/', login_required(logout_user), name='logout'),
    path('clients/', include(('apps.clients.urls', 'clients'))),
    path('products/', include(('apps.products.urls', 'products'))),
    path('providers/', include(('apps.providers.urls', 'providers'))),
    path('sales/', include(('apps.sales.urls', 'sales'))),
    path('users/', include(('apps.users.urls', 'users'))),
    path('accounts/', include(('apps.accounts.urls', 'accounts'))),
]

apps/accounts/models.py
import decimal

from django.db import models
from apps.users.models import User, Subsidiary


# Create your models here.


class Account(models.Model):
    TYPE_CHOICES = (('E', 'CAJA DE EFECTIVO'), ('B', 'CUENTA BANCARIA'))
    id = models.AutoField(primary_key=True)
    name = models.CharField('Nombre', max_length=50)
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES)
    initial = models.DecimalField(max_digits=10, decimal_places=2, default='0')
    subsidiary = models.ForeignKey('users.Subsidiary', on_delete=models.SET_NULL, null=True, blank=True)
    create_at = models.DateTimeField(auto_now=True)

    def get_status(self):
        status = 'C'
        payment_set = Payments.objects.filter(account=self, status='R', type__in=['A', 'C'])
        if payment_set.exists():
            status = payment_set.last().type
            return status
        else:
            return status

    def total(self):
        from apps.accounts.views import get_total
        total = get_total(account_obj=self)
        t = decimal.Decimal(0.00)
        if total:
            t = total[0].get('total')
        return t

    class Meta:
        verbose_name = 'Cuenta'
        verbose_name_plural = 'Cuentas'
        ordering = ['id']

    def __str__(self):
        return self.name


class Payments(models.Model):
    TYPE_CHOICES = (('I', 'Ingreso'), ('E', 'Egreso'), ('A', 'Apertura'), ('C', 'Cierre'))
    STATUS_CHOICES = (('R', 'Realizado'), ('A', 'Anulado'))
    PAYMENT_CHOICES = (('P', 'Pagado'), ('C', 'Credito'))
    id = models.AutoField(primary_key=True)
    status = models.CharField('Estado', max_length=1, choices=STATUS_CHOICES, default='R')
    type = models.CharField('Tipo', max_length=1, choices=TYPE_CHOICES)
    payment = models.CharField('Pago', max_length=1, choices=PAYMENT_CHOICES, default='P')
    order = models.ForeignKey('sales.Order', on_delete=models.CASCADE, null=True, blank=True)
    code = models.CharField('Codigo de operacion', max_length=50, null=True, blank=True)
    description = models.CharField('Descripcion de la operacion', max_length=250, default='-')
    amount = models.DecimalField('Monto', max_digits=10, decimal_places=2, default=0)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    date_payment = models.DateField(null=True, blank=True)
    user = models.ForeignKey(User, verbose_name='Usuario', on_delete=models.CASCADE, null=True, blank=True)
    account = models.ForeignKey('accounts.Account', verbose_name='E/B', on_delete=models.SET_NULL, null=True, blank=True)
    number = models.IntegerField(verbose_name='Numero', null=True, blank=True)
    subsidiary = models.ForeignKey(Subsidiary, verbose_name='Filial', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = 'Pago'
        verbose_name_plural = 'Pagos'
        ordering = ['id']

    def __str__(self):
        return str(self.id)

apps/sales/models.py
import decimal
from django.db import models
from django.db.models import Sum, F
from django.db.models.functions import Coalesce

from apps.users.models import User
from django.utils import timezone

now = timezone.now()


# Create your models here.
class Order(models.Model):
    TYPE_CHOICES = (
        ('V', 'VENTA'),
        ('C', 'COMPRA'),
        ('M', 'EMPEÑO'),
        ('R', 'ENTREGA'),
        ('E', 'ENTRADA'),
        ('S', 'SALIDA')
    )
    STATUS_CHOICES = (('C', 'COMPLETADO'), ('P', 'PENDIENTE'), ('A', 'ANULADO'))
    id = models.AutoField(primary_key=True)
    type = models.CharField('TIPO', max_length=1, choices=TYPE_CHOICES, default='V')
    number = models.IntegerField(verbose_name='CORRELATIVO', null=True, blank=True)
    status = models.CharField('ESTADO', max_length=1, choices=STATUS_CHOICES, default='P')
    init = models.DateField(null=True, blank=True)
    end = models.DateField(null=True, blank=True)
    current = models.DateField(null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    client = models.ForeignKey('clients.Client', verbose_name='CLIENTE',
                               on_delete=models.SET_NULL, null=True, blank=True)
    provider = models.ForeignKey('providers.Provider', verbose_name='PROVEEDOR',
                                 on_delete=models.SET_NULL, null=True, blank=True)
    subsidiary = models.ForeignKey('users.Subsidiary', on_delete=models.CASCADE, null=True, blank=True)
    relative = models.IntegerField(verbose_name='ORDER RELACIONAL', default=0)

    def total(self):
        total = Detail.objects.filter(order=self).aggregate(
            r=Coalesce(Sum(F('quantity') * F('price')), decimal.Decimal(0.00))).get('r')
        return round(total, 2)

    class Meta:
        verbose_name = 'Orden'
        verbose_name_plural = 'Ordenes'
        ordering = ['id']

    def __str__(self):
        return str(self.type) + "-" + str(self.number)


class Detail(models.Model):
    id = models.AutoField(primary_key=True)
    order = models.ForeignKey('sales.Order', on_delete=models.CASCADE, null=True, blank=True)
    product = models.ForeignKey('products.Product', on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.DecimalField('Cantidad', max_digits=10, decimal_places=2, default=0)
    old_quantity = models.DecimalField('Cantidad Anterior', max_digits=10, decimal_places=2, default=0)
    price = models.DecimalField('Precio', max_digits=10, decimal_places=2, default=0)

    def amount(self):
        amount = round(decimal.Decimal(self.quantity * self.price), 2)
        return amount

    class Meta:
        verbose_name = 'Detalle'
        verbose_name_plural = 'Detalles'
        ordering = ['id']

    def __str__(self):
        return str(self.id)

templates/sales/modal_return_pawns.html
{% load static %}
<div class="modal-dialog modal-dialog-centered modal-xl" role="document">
    <div class="modal-content">
        <div class="modal-header bg-primary">
            <h6 class="modal-title  text-white ">DEVOLUCION DEL PRODUCTO</h6>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="modal-body p-2">
            <div class="card border-primary">
                <div class="card-header">
                    <div class="row">
                        <div class="col-sm-6 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="measures">Caja/Cuenta</label>
                                <select class="form-control" id="account" name="account">
                                    {% for a in account_set %}
                                        <option value="{{ a.id }}">{{ a.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-3 col-md-3 col-lg-3">
                            <div class="form-group">
                                <label for="name">Monto Pagar</label>
                                <input type="number" step="0.01" min="0.00" class="form-control text-right" id="amount"
                                       name="amount"
                                       placeholder="0.00" value="">
                                <input type="hidden" value="{{ order_obj.id }}" id="order" name="order">
                            </div>
                        </div>
                        <div class="col-sm-3 col-md-3 col-lg-3">
                            <div class="form-group">
                                <label for="measures">Codigo</label>
                                <input type="text" class="form-control" id="code" name="code" placeholder="Codigo ..." value="">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body p-3">
                    <div class="row">
                        <div class="col-sm-3 col-md-3 col-lg-3">
                            <div class="form-group">
                                <label for="measures">Fecha</label>
                                <input type="date" class="form-control" id="date" name="date" value="{{ date }}">
                            </div>
                        </div>
                        <div class="col-sm-3 col-md-3 col-lg-3">
                            <div class="form-group">
                                <label for="measures">Nº Documento</label>
                                <input type="text" class="form-control" id="dni" name="dni" disabled
                                       placeholder="DNI ..." value="{{ order_obj.provider.document }}">
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6 col-lg-6">
                            <div class="form-group">
                                <label for="name">Nombres</label>
                                <input type="text" class="form-control" id="names" name="names" disabled
                                       placeholder="Ingrese nombres" value="{{ order_obj.provider.names }}">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12">
                            <table class="table table-striped">
                                <thead>
                                <tr class="text-center text-warning text-uppercase" style="width: 100%">
                                    <th style="width: 5%">Nº</th>
                                    <th style="width: 12%">Cantidad</th>
                                    <th style="width: 47%">Descripcion</th>
                                    <th style="width: 12%">Medida</th>
                                    <th style="width: 12%">Precio</th>
                                    <th style="width: 12%">Importe</th>
                                    {#                            <th style="width: 10%">Eliminar</th>#}
                                </tr>
                                </thead>
                                <tbody id="order_detail">
                                {% for d in order_obj.detail_set.all %}
                                    <tr class="p-0" product="{{ d.product.id }}" pk="{{ d.id }}"
                                        i="{{ forloop.counter }}" old="{{ d.quantity }}">
                                        <td class="align-middle item-number p-1 text-center"><span
                                                class="bs-stepper-circle bg-primary">{{ forloop.counter }}</span></td>
                                        <td class="align-middle item-quantity p-1"><input type="number" step="1" min="1"
                                                                                          max="{{ d.quantity|safe }}"
                                                                                          placeholder="0.00"
                                                                                          class="form-control text-center value-quantity"
                                                                                          disabled
                                                                                          value="{{ d.quantity|safe }}"/>
                                        </td>
                                        <td class="align-middle item-description p-1 text-justify">{{ d.product.name }}</td>
                                        <td class="align-middle item-unit p-1 text-center">UND
                                        <td class="align-middle item-price p-1 text-right"><input type="number"
                                                                                                  step="0.01"
                                                                                                  placeholder="0.00"
                                                                                                  class="form-control text-right value-price"
                                                                                                  value="{{ d.price|safe }}"/>
                                        </td>
                                        <td class="align-middle item-amount p-1 text-right">
                                            {{ d.amount|safe }}
                                        </td>
                                        {#                                <td class="align-middle item-delete p-1 text-center">#}
                                        {#                                    <button type="button" class="btn btn-danger rounded"><i class="fa fa-trash-alt"></i></button>#}
                                        {#                                </td>#}
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal-footer p-1">
            <button type="button" class="btn btn-secondary" id="btn-modal-close" data-dismiss="modal">Cerrar</button>
            &nbsp;
            <button id="create-return" onclick="SaveReturn()" type="button" class="btn btn-primary">Registrar entrega
            </button>
        </div>
    </div>
</div>
<script type="text/javascript" src="{% static 'js/sales/ModalReturnPawns.js' %}">
</script>

templates/sales/purchases.html
{% extends 'home.html' %}
{% load static %}
{% block title %}
    Compras
{% endblock title %}
{% block headerleft %}
    Compras
{% endblock headerleft %}
{% block headerright %}
    Compras
{% endblock headerright %}

{% block body %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <h5 class="card-title">Orden de Compras</h5>
                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-address-card"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Documento" id="document"
                                       name="document">
                                <input type="hidden" class="form-control" id="provider" name="provider" value="">
                            </div>
                            <!-- /input-group -->
                        </div>
                        <!-- /.col-lg-4 -->
                        <div class="col-lg-8">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user-alt"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Nombres Apellidos..." id="names"
                                       name="names">
                            </div>
                            <!-- /input-group -->
                        </div>
                        <!-- /.col-lg-4 -->
                        <div class="col-lg-2">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone-volume"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Celular" id="phone" name="phone">
                            </div>
                            <!-- /input-group -->
                        </div>
                        <!-- /.col-lg-4 -->
                    </div>
                    <div class="row">
                        <div class="col-lg-10">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-house-damage"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Direccion de domicilio..."
                                       id="address" name="address">
                            </div>
                            <!-- /input-group -->
                        </div>
                        <!-- /.col-lg-4 -->
                        <div class="col-lg-2">
                            <div class="input-group mb-3">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                                </div>
                                <input type="date" class="form-control" placeholder="Fecha" value="{{ date }}"
                                       id="date_current" name="date_current">
                            </div>
                            <!-- /input-group -->
                        </div>
                        <!-- /.col-lg-4 -->
                    </div>
                </div>
                <!-- ./card-body -->
                {#                <div class="card-footer">#}
                {##}
                {#                </div>#}
                <!-- /.card-footer -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-lg-7 align-self-center pt-1 pb-1">
                            <div id="autocomplete-product" class="autocomplete text-primary">
                                <input class="form-control autocomplete-input" id="search-product"
                                       name="search-product"
                                       placeholder="Buscar producto"/>
                                <ul class="autocomplete-result-list"></ul>
                            </div>
                        </div>
                        <div class="col-lg-3 align-self-center pt-1 pb-1">
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-search"></i></span>
                                </div>
                                <input type="text" class="form-control" placeholder="Buscar orden..." id="order-search"
                                       name="order-search">
                                <input type="hidden" class="form-control" id="order" name="order" value="">
                            </div>
                        </div>
                        <div class="col-lg-2 align-self-center pt-1 pb-1">
                            <div class="row">
                                <div class="col-lg-6 p-1">
                                    <button type="button" class="btn btn-primary w-100" id="btn-cancel"
                                            onclick="CleanPurchase()">
                                        Cancelar
                                    </button>
                                </div>
                                <div class="col-lg-6 p-1">
                                    <button type="button" class="btn btn-success w-100" id="btn-save"
                                            onclick="CreatePurchase()">
                                        Guardar
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-header -->
                <div class="card-body table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr class="text-center text-warning text-uppercase" style="width: 100%">
                            <th style="width: 5%">Nº</th>
                            <th style="width: 10%">Cantidad</th>
                            <th style="width: 45%">Descripcion</th>
                            <th style="width: 10%">Medida</th>
                            <th style="width: 10%">Precio</th>
                            <th style="width: 10%">Importe</th>
                            <th style="width: 10%">Eliminar</th>
                        </tr>
                        </thead>
                        <tbody id="order_detail">

                        </tbody>
                    </table>
                </div>
                <!-- ./card-body -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col-lg-9">
                            <div class="row">
                                <div class="col-sm-6 col-md-6 col-lg-6">
                                    <div class="form-group">
                                        <label for="measures">Caja/Cuenta</label>
                                        <select class="form-control" id="account" name="account" pk="">
                                            <option value="">SELECCIONE</option>
                                            {% for a in account_set %}
                                                <option value="{{ a.id }}">{{ a.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <div class="form-group">
                                        <label for="name">Monto Pagar</label>
                                        <input type="number" step="0.01" min="0.00" class="form-control text-right"
                                               id="amount"
                                               name="amount"
                                               placeholder="0.00" value="">
                                        <input type="hidden" value="{{ order_obj.id }}" id="order" name="order">
                                    </div>
                                </div>
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <div class="form-group">
                                        <label for="measures">Codigo</label>
                                        <input type="text" class="form-control" id="code" name="code"
                                               placeholder="Codigo ..." value="">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-3">
                            <label class="text-warning">TOTAL</label>
                            <div class="input-group mb-2">
                                <div class="input-group-prepend">
                                    <span class="input-group-text p-0"><span
                                            class="small bs-stepper-circle bg-primary m-0 ml-1 mr-1">S/.</span>
                                    </span>
                                </div>
                                <input type="text" class="form-control text-right font-weight-bold" disabled id="total"
                                       name="total" placeholder="0.00">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.card-footer -->
            </div>
            <!-- /.card -->
        </div>
        <!-- /.col -->
    </div>
    <div class="modal fade" id="modal-product" tabindex="-1" role="dialog"
         aria-labelledby="ModalHelpTitle"
         aria-hidden="true"></div>
{% endblock body %}

{% block extrajs %}
    <script type="text/javascript" src="{% static 'js/sales/PurchaseList.js' %}"></script>
{% endblock extrajs %}

templates/sales/returns_grid_list.html
<table class="table table-hover table-striped">
    <tbody id="table_return_list">
    {% for o in order_set %}
        <tr style="width: 100%">
            <td class="align-middle" style="width: 5%">
                <div class="icheck-warning">
                    <input type="checkbox" value="" id="{{ o.id }}">
                    <label for="{{ o.id }}"></label>
                </div>
            </td>
            <td class="mailbox-name align-middle" style="width: 6%">{{ o.get_type_display }}</td>
            <td class="mailbox-name align-middle i-status" style="width: 9%">
                {% if o.status == 'C' %}
                    <i class="fas fa-star text-success"></i>
                {% elif o.status == 'P' %}
                    <i class="fas fa-star text-warning"></i>
                {% else %}
                    <i class="fas fa-star text-danger"></i>
                {% endif %}
                {{ o.get_status_display }}
            </td>
            <td class="mailbox-name align-middle" style="width: 6%">Nº {{ o.number }}</td>
            <td class="mailbox-name align-middle" style="width: 10%">{{ o.current|date:'d-m-Y' }}</td>
            <td class="mailbox-name align-middle" style="width: 10%">{{ o.create_at|date:'d-m-Y' }}</td>
            <td class="mailbox-name align-middle" style="width: 20%"><a href="">{{ o.provider.names }}</a></td>
            <td class="mailbox-subject align-middle" style="width: 30%">
                {% for d in o.detail_set.all %}
                    <div class="card m-0 collapsed-card">
                        <div class="card-header">
                            <h3 class="card-title">LISTADO DE PRODUCTOS</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body" style="display: none;">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item active">
                                    <a href="#" class="nav-link p-1">
                                        <div class="row">
                                            <div class="col-md-6 text-left">
                                                <i class="fas fa-chevron-circle-right"></i> {{ d.product.name }}
                                            </div>
                                            <div class="col-md-3 text-right">{{ d.quantity|safe }}</div>
                                            <div class="col-md-3 text-right">{{ d.price|safe }}</div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>

                    </div>
                {% empty %}
                    <i class="fas fa-circle text-warning"></i> SIN DETALLE
                {% endfor %}
            </td>
            <td class="mailbox-star align-middle" style="width: 4%">
                <button type="button" class="btn btn-warning" onclick="showModalReturn({{ o.id }})"><i
                        class="fas fa-check-circle text-white"></i></button>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>